Jellyfin.Plugin.Listenbrainz/Api/LbApiClient.cs, Jellyfin.Plugin.Listenbrainz/Jellyfin.Plugin.Listenbrainz.csproj, Jellyfin.Plugin.Listenbrainz/Models/Musicbrainz/Responses/RecordingIdResponse.cs
Closes #1 
Handle out of range exceptions and remove invalid track MBID from listen request when no recording ID is found.
=> Handle invalid track MBIDs

Jellyfin.Plugin.Listenbrainz.JF108/Jellyfin.Plugin.Listenbrainz.JF108.csproj, Jellyfin.Plugin.Listenbrainz.Tests/BaseListenbrainzClientTest.cs, Jellyfin.Plugin.Listenbrainz/Clients/BaseHttpClient.cs, Jellyfin.Plugin.Listenbrainz/Clients/BaseListenbrainzClient.cs, Jellyfin.Plugin.Listenbrainz/Clients/BaseMusicbrainzClient.cs, Jellyfin.Plugin.Listenbrainz/Clients/DummyMusicbrainzClient.cs, Jellyfin.Plugin.Listenbrainz/Clients/ListenbrainzClient.cs, Jellyfin.Plugin.Listenbrainz/Clients/MusicbrainzClient.cs, Jellyfin.Plugin.Listenbrainz/Configuration/GlobalConfiguration.cs, Jellyfin.Plugin.Listenbrainz/Configuration/PluginConfiguration.cs, Jellyfin.Plugin.Listenbrainz/Configuration/configPage.html, Jellyfin.Plugin.Listenbrainz/Controllers/PluginController.cs, Jellyfin.Plugin.Listenbrainz/Jellyfin.Plugin.Listenbrainz.csproj, Jellyfin.Plugin.Listenbrainz/Resources/Listenbrainz/Api.cs, Jellyfin.Plugin.Listenbrainz/Resources/Listenbrainz/Endpoints.cs, Jellyfin.Plugin.Listenbrainz/Resources/Musicbrainz/Api.cs, Jellyfin.Plugin.Listenbrainz/ServerEntryPoint.cs, Jellyfin.Plugin.Listenbrainz/Services/IMusicbrainzClientService.cs, README.md
#17 
Users may want to use other instances compatible with Listenbrainz/Musicbrainz.
TODO:
=> Allow configuration of custom base API URLs

.github/RELEASE.md, .gitignore, Jellyfin.Plugin.Listenbrainz/Configuration/GlobalConfiguration.cs, Jellyfin.Plugin.Listenbrainz/Configuration/configPage.html, Jellyfin.Plugin.Listenbrainz/Models/TrackedAudio.cs, Jellyfin.Plugin.Listenbrainz/ServerEntryPoint.cs, Jellyfin.Plugin.Listenbrainz/Services/PlaybackTracker/DefaultPlaybackTracker.cs, Jellyfin.Plugin.Listenbrainz/Services/PlaybackTracker/IPlaybackTrackerService.cs, Jellyfin.Plugin.Listenbrainz/Services/PlaybackTracker/PlaybackTracker.cs, Jellyfin.Plugin.Listenbrainz/Utils/Helpers.cs, README.md, jellyfin.ruleset, version.json
Requested in #25.
Use `UserDataSaved` event as an alternative method for listen recognition.
=> Alternative listen recognition mode 

build.yaml, src/Jellyfin.Plugin.ListenBrainz/Plugin.cs
Workaround for #42, until resolved in Jellyfin server.
=> Work around jellyfin resolving invalid path

build.yaml, src/Jellyfin.Plugin.ListenBrainz/Configuration/configurationPage.html
Fixes API token error mentioned in #44
=> Fix api token read error

build.yaml, src/Jellyfin.Plugin.ListenBrainz/Extensions/AudioExtensions.cs
=> Allow `/` for a MBID delimiter

src/Jellyfin.Plugin.ListenBrainz.Api/BaseClient.cs, tests/Jellyfin.Plugin.ListenBrainz.Api.Tests/JsonEncodeTests.cs
Fix missing value for feedback (score) if the feedback was neutral.
Found in #52.
=> Fix feedback sync

code.ruleset, src/Jellyfin.Plugin.ListenBrainz.Api/BaseApiClient.cs, src/Jellyfin.Plugin.ListenBrainz.Api/BaseClient.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Resources/Headers.cs, tests/Jellyfin.Plugin.ListenBrainz.Api.Tests/BaseApiClientTests.cs, tests/Jellyfin.Plugin.ListenBrainz.Api.Tests/Jellyfin.Plugin.ListenBrainz.Api.Tests.csproj
=> Implement rate limiter for ListenBrainz API

src/Jellyfin.Plugin.ListenBrainz.Api/BaseApiClient.cs
Correctly synchronize async threads in rate limiter introduced in #53.
=> Fix synchronization in rate limiter

doc/how-it-works.md, src/Jellyfin.Plugin.ListenBrainz.Api/Interfaces/IListenBrainzApiClient.cs, src/Jellyfin.Plugin.ListenBrainz.Api/ListenBrainzApiClient.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Models/Listen.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Models/Requests/GetUserListensRequest.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Models/Responses/GetUserListensResponse.cs, src/Jellyfin.Plugin.ListenBrainz/Clients/ListenBrainzClient.cs, src/Jellyfin.Plugin.ListenBrainz/Configuration/UserConfig.cs, src/Jellyfin.Plugin.ListenBrainz/Configuration/configurationPage.html, src/Jellyfin.Plugin.ListenBrainz/Controllers/PluginController.cs, src/Jellyfin.Plugin.ListenBrainz/Dtos/ValidatedToken.cs, src/Jellyfin.Plugin.ListenBrainz/Interfaces/IListenBrainzClient.cs, src/Jellyfin.Plugin.ListenBrainz/PluginImplementation.cs
If a recording MBID is not available for favorite sync, try getting recroding MSID from ListenBrainz and use it.
Closes #58
=> Implement favorite sync fallback using MSID

build.yaml, doc/how-it-works.md, src/Jellyfin.Plugin.ListenBrainz/PluginImplementation.cs
=> Fix MSID favorite sync exception crashing the server

build.yaml, src/Jellyfin.Plugin.ListenBrainz.Api/Models/AdditionalInfo.cs
Use correct attribute for JSON serializer, closes #71
=> Use correct attribute for serializer

src/Jellyfin.Plugin.ListenBrainz/Dtos/StoredListen.cs, src/Jellyfin.Plugin.ListenBrainz/Interfaces/ICacheManager.cs, src/Jellyfin.Plugin.ListenBrainz/Interfaces/IListensCache.cs, src/Jellyfin.Plugin.ListenBrainz/Managers/CacheManager.cs, src/Jellyfin.Plugin.ListenBrainz/Managers/ListensCacheManager.cs, src/Jellyfin.Plugin.ListenBrainz/PluginImplementation.cs, src/Jellyfin.Plugin.ListenBrainz/Tasks/ResubmitListensTask.cs, tests/Jellyfin.Plugin.ListenBrainz.Tests/ListenCacheTests.cs, tests/Jellyfin.Plugin.ListenBrainz.Tests/ListensCacheTests.cs
Fix listens cache:
- rename class
- thread-safe locking
- async and sync methods
- re-add tests
=> Listens cache fixes

src/Jellyfin.Plugin.ListenBrainz/Clients/MetadataClient.cs, src/Jellyfin.Plugin.ListenBrainz/Configuration/configurationPage.html
Fix configuring of custom MusicBrainz instance (base API URL) after migrating to the official API client.
=> Fix configuring of custom MusicBrainz instance

.github/workflows/publish.yml, .github/workflows/publish_dev.yml
Upgrade JPRM from ancient version which should hopefully fix compilation issues.
Related to #86
=> Upgrade jprm in publish workflows

.github/workflows/build.yml, README.md, build.yaml, src/Jellyfin.Plugin.ListenBrainz.Api/BaseApiClient.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Jellyfin.Plugin.ListenBrainz.Api.csproj, src/Jellyfin.Plugin.ListenBrainz.Api/Models/Requests/GetUserFeedbackRequest.cs, src/Jellyfin.Plugin.ListenBrainz.Api/Models/Requests/GetUserListensRequest.cs, src/Jellyfin.Plugin.ListenBrainz.Common/Jellyfin.Plugin.ListenBrainz.Common.csproj, src/Jellyfin.Plugin.ListenBrainz.Http/Jellyfin.Plugin.ListenBrainz.Http.csproj, src/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.csproj, src/Jellyfin.Plugin.ListenBrainz/Dtos/JellyfinMediaLibrary.cs, src/Jellyfin.Plugin.ListenBrainz/EntryPoint.cs, src/Jellyfin.Plugin.ListenBrainz/Extensions/LibraryManagerExtensions.cs, src/Jellyfin.Plugin.ListenBrainz/Jellyfin.Plugin.ListenBrainz.csproj, src/Jellyfin.Plugin.ListenBrainz/Plugin.cs, src/Jellyfin.Plugin.ListenBrainz/PluginImplementation.cs, src/Jellyfin.Plugin.ListenBrainz/PluginService.cs, src/Jellyfin.Plugin.ListenBrainz/Tasks/LovedTracksSyncTask.cs, tests/Jellyfin.Plugin.ListenBrainz.Api.Tests/Jellyfin.Plugin.ListenBrainz.Api.Tests.csproj, tests/Jellyfin.Plugin.ListenBrainz.Api.Tests/JsonEncodeTests.cs, tests/Jellyfin.Plugin.ListenBrainz.Http.Tests/Jellyfin.Plugin.ListenBrainz.Http.Tests.csproj, tests/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.Tests/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.Tests.csproj, tests/Jellyfin.Plugin.ListenBrainz.Tests/Jellyfin.Plugin.ListenBrainz.Tests.csproj
- Upgrade to .NET 8
- Make plugin compatible with Jellyfin 10.9.x
Closes #92 
TODO:
=> Compatibility for Jellyfin 10.9.x

build.yaml, src/Jellyfin.Plugin.ListenBrainz.Common/Extensions/EnumerableExtensions.cs, src/Jellyfin.Plugin.ListenBrainz/Tasks/LovedTracksSyncTask.cs
=> Fix handling expections in loved tracks sync (backport of #98)

build.yaml
=> Release 4.0.2.0

build.yaml, src/Jellyfin.Plugin.ListenBrainz/Plugin.cs, tests/Jellyfin.Plugin.ListenBrainz.Tests/MockPlugin.cs
=> Fix plugin crashing server

src/Jellyfin.Plugin.ListenBrainz/Clients/ListenBrainzClient.cs, src/Jellyfin.Plugin.ListenBrainz/Interfaces/IPluginConfigService.cs, src/Jellyfin.Plugin.ListenBrainz/Plugin.cs, src/Jellyfin.Plugin.ListenBrainz/PluginImplementation.cs, src/Jellyfin.Plugin.ListenBrainz/PluginService.cs, src/Jellyfin.Plugin.ListenBrainz/Services/DefaultPluginConfigService.cs
Improve testability by:
- using interface (DI) in consumers
- avoiding usage of static methods
=> Access plugin configuration through config service
